### ISSUE TITLE
Summary module swaps LR to RL orientation 

### ISSUE THREAD

**Issue by zhemingfan** [bcgsc/mavis#319] opened 2022-03-04 19:15 UTC
Currently calls which are correctly called as LR are being swapped to RL in the summary module. 

Traceback (most recent call last):
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/venv/bin/mavis", line 33, in <module>
    sys.exit(load_entry_point('mavis', 'console_scripts', 'mavis')())
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/src/mavis/main.py", line 295, in main
    raise err 
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/src/mavis/main.py", line 255, in main
    summary_main.main(
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/src/mavis/summary/main.py", line 217, in main
    grouped, removed = group_by_distance(bpp_set, distances)
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/src/mavis/summary/summary.py", line 191, in group_by_distance
    grouped_calls.append(group_events(pairs))
  File "/projects/jfan_prj/jfan_prj/MAVIS/mavis/src/mavis/summary/summary.py", line 137, in group_events
    raise AssertionError('cannot group events differing on key elements', bpp, new_bpp)
AssertionError: ('cannot group events differing on key elements', 'BPP(Breakpoint(1:3522792-3522852L), Breakpoint(1:3522805-3522839R), opposing=False, tracking_id=vcf-cuteSV.INS.74)', 'BPP(Breakpoint(1:3522792-3522839R), Breakpoint(1:3522792-3522852L    ), opposing=False)')

**Comment by creisle** [comment] 2022-03-04 19:31
After our debugging discussion offline we have narrowed down the cause of this error. When breakpoints are being grouped in the summary module a new breakpoint is created from the grouped breakpoints. However when a new breakpoint pair is created we auto-sort the breakpoints before assigning then 1/2 here

https://github.com/bcgsc/mavis/blob/479fdeb3b21fa40eeb80f4b43e556483c2144041/src/mavis/breakpoint.py#L263

This sort method is insufficient when the breakpoint intervals are imprecise ranges. Overall there are 2 things to fix for this bug

- [ ] change the breakpoint sort in BreakpointPair to not sort when the ranges overlap
- [ ] change the convert module to not allow start ranges which encompass areas past the end range

In this instance we are seeing the bizzarre SV that looks like this

```
ref       -------------------------------------------------------------------------------
break1 ------------------------=======================--------------
break2 ------------------------==========-------------------------------------
```

which should be impossible

**Closed** 2022-05-06 19:12 UTC
Labels: bug
